addons:
  chrome: stable
language: ruby

before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter -d before-build
after_script:
  - ./cc-test-reporter -d after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT

services:
  - mysql
  - redis
  - elasticsearch

dist: xenial
