sudo: required
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
language: ruby

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /usr/bin
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:setup
